# Generated by Django 2.2.5 on 2019-09-19 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('geojson', models.TextField()),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('created_time', models.DateTimeField()),
                ('changed_time', models.DateTimeField()),
                ('lamning_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LamningType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
