# Generated by Django 2.2.5 on 2019-09-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lamning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamning',
            name='changed_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lamning',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
