# Generated by Django 2.2.5 on 2019-09-21 14:40

import core.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190921_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamning',
            name='geojson',
            field=models.TextField(validators=[core.utilities.validate_geojson]),
        ),
    ]
