# Generated by Django 2.2.5 on 2019-09-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190921_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='raa_lamning',
            field=models.TextField(blank=True),
        ),
    ]
