# Generated by Django 2.2.5 on 2019-11-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190921_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='lamning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Lamning'),
        ),
    ]
