# Generated by Django 4.0 on 2021-12-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_region_pointofinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointofinterest',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='region',
            name='wd',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
