# Generated by Django 4.0 on 2021-12-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pointofinterestcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamningtype',
            name='description',
            field=models.TextField(default='Se Kulturmiljöregistret.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lamningtype',
            name='wikipedia',
            field=models.TextField(null=True),
        ),
    ]
