# Generated by Django 4.0 on 2022-01-07 01:02

from django.db import migrations


def title_from_type(apps, schema_editor):
    Lamning = apps.get_model('core', 'Lamning')
    for lamning in Lamning.objects.all():
        lamning.title = lamning.lamning_type.name
        lamning.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_lamning_title'),
    ]

    operations = [
        migrations.RunPython(title_from_type),
    ]
