# Generated by Django 4.0 on 2022-01-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220110_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lamning',
            name='lamning_type',
        ),
        migrations.DeleteModel(
            name='LamningType',
        ),
    ]
