# Generated by Django 4.0 on 2022-02-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_lamning_lamning_type_delete_lamningtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lamning',
            options={'ordering': ['-created_time']},
        ),
    ]
