# Generated by Django 4.0.2 on 2022-03-18 10:15
# https://docs.djangoproject.com/en/4.0/topics/migrations/#data-migrations-1

from django.db import migrations

# https://django-taggit.readthedocs.io/en/latest/custom_tagging.html#using-a-custom-tag-or-through-model
def migrate_tags(apps, schema_editor):
    '''Migrate taggit tags to custom taggit model'''
    Tag = apps.get_model('taggit', 'Tag')
    CustomTag = apps.get_model('core', 'CustomTag')
    for tag in Tag.objects.all():
        CustomTag.objects.get_or_create(name=tag.name, slug=tag.slug)

def set_tags(apps, schema_editor):
    '''Replace old tag with new tag'''
    TaggedItem = apps.get_model('taggit', 'TaggedItem')
    TaggedThing = apps.get_model('core', 'TaggedThing')
    CustomTag = apps.get_model('core', 'CustomTag')

    for tagged_item in TaggedItem.objects.all():
        new_tag = CustomTag.objects.get(name=tagged_item.tag.name)
        TaggedThing.objects.get_or_create(
            content_type_id=tagged_item.content_type_id,
            object_id=tagged_item.object_id,
            tag=new_tag,
        )

class Migration(migrations.Migration):
    '''Migrate taggit tags to custom taggit model'''

    dependencies = [
        ('core', '0025_customtag_taggedthing'),
    ]

    operations = [
        migrations.RunPython(migrate_tags),
        migrations.RunPython(set_tags),
    ]
