# Generated by Django 4.0.2 on 2022-03-18 12:45

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220318_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamning',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='core.TaggedThing', to='core.CustomTag', verbose_name='Tags'),
        ),
    ]
