# Generated by Django 4.0.2 on 2022-04-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_lamning_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtag',
            name='wikipedia',
            field=models.TextField(blank=True),
        ),
    ]
