# Generated by Django 4.1 on 2022-12-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_customtag_slug_delete_invitecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofinterestcomment',
            name='poi',
        ),
        migrations.RemoveField(
            model_name='pointofinterestcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.DeleteModel(
            name='PointOfInterestComment',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
