# Generated by Django 4.1 on 2022-12-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_pointofinterestcomment_poi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LamningWikipediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmr_lamning', models.UUIDField()),
                ('wikipedia', models.URLField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
