# Generated by Django 4.1 on 2022-12-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_lamningwikipedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMRLamningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('raa_id', models.IntegerField()),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
