# Generated by Django 4.1.7 on 2023-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_kmrlamningtype_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.UUIDField()),
                ('target', models.URLField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('changed_time', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('publisher', models.TextField()),
                ('author_name_string', models.TextField(blank=True)),
                ('target_type', models.TextField(blank=True)),
            ],
        ),
    ]
