# Generated by Django 4.1.7 on 2023-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(blank=True, choices=[('SR', 'Skaderapport')], max_length=2),
        ),
    ]
