# Generated by Django 4.1.7 on 2023-09-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_privacy',
            field=models.CharField(choices=[('PU', 'Alla'), ('ME', 'Inloggade FornPunkt användare'), ('PR', 'Bara du')], default='PR', max_length=2),
        ),
    ]
