# Generated by Django 4.1.7 on 2023-09-28 14:02

from django.db import migrations

def create_user_details_for_each_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserDetails = apps.get_model('core', 'UserDetails')
    for user in User.objects.all():
        UserDetails.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_userdetails_profile_privacy'),
    ]

    operations = [
        migrations.RunPython(create_user_details_for_each_user),
    ]
