# Generated by Django 4.1.7 on 2023-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20230928_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_description',
            field=models.TextField(blank=True),
        ),
    ]
