# Generated by Django 5.0.2 on 2025-03-29 20:52

import core.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_userdetails_user_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lamning",
            name="observation_type",
            field=models.CharField(
                blank=True,
                choices=[("FO", "Fältobservation"), ("RO", "Fjärrobservation"), ("MO", "Maskinobservation")],
                max_length=2,
                validators=[core.utilities.validate_observation_type],
            ),
        ),
    ]
