# Generated by Django 5.1.4 on 2025-11-06 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_lamning_observation_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShadowLamning",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(unique=True)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("geojson", models.TextField(blank=True)),
                ("center_lat", models.FloatField(blank=True, null=True)),
                ("center_lon", models.FloatField(blank=True, null=True)),
                ("lamning_type", models.TextField(blank=True)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Shadow Lamning",
                "verbose_name_plural": "Shadow Lamnings",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("changed_time", models.DateTimeField(auto_now=True)),
                ("hidden", models.BooleanField(default=False)),
                ("lamnings", models.ManyToManyField(blank=True, related_name="in_lists", to="core.lamning")),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "shadow_lamnings",
                    models.ManyToManyField(blank=True, related_name="in_lists", to="core.shadowlamning"),
                ),
            ],
            options={
                "verbose_name": "List",
                "verbose_name_plural": "Lists",
                "ordering": ["-created_time"],
            },
        ),
    ]
