# Generated by Claude Code on 2025-10-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_lamning_observation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='orcid_id',
            field=models.CharField(
                blank=True,
                help_text='ORCID iD (e.g., 0000-0002-1825-0097)',
                max_length=19,
                null=True,
                unique=True
            ),
        ),
    ]
