"""
Django settings for fornfind project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

import dj_database_url
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!

if 'FP_ENVIRONMENT' in os.environ and os.environ['FP_ENVIRONMENT'] == 'production':
    DEBUG = False
    ALLOWED_HOSTS = [os.environ['DJANGO_ALLOWED_HOSTS']]
    SECRET_KEY = os.environ['FP_SECRET_KEY']
    ADMIN_PATH = os.environ.get('ADMIN_PATH')
    HASHIDS_SALT = os.environ.get('HASHIDS_SALT')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = True

    LANTMATERIET_USERNAME = os.environ.get('LANTMATERIET_USERNAME')
    LANTMATERIET_PASSWORD = os.environ.get('LANTMATERIET_PASSWORD')

    if os.getenv('DATABASE_URL', None) is None:
        raise Exception('DATABASE_URL environment variable not defined')
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL')),
    }

    sentry_sdk.init(
        dsn=os.environ['SENTRY_DSN_URI'],
        integrations=[DjangoIntegration()],
        environment='production',

        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        traces_sample_rate=1.0,

        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth) you may enable sending PII data.
        send_default_pii='SENTRY_SEND_DEFAULT_PII' in os.environ and os.environ['SENTRY_SEND_DEFAULT_PII'].lower() == 'true'
    )

else:
    DEBUG = True
    INTERNAL_IPS = ['127.0.0.1']
    ALLOWED_HOSTS = []
    SECRET_KEY = '&i%4-cwm(_&yiiq-qkte(u*vwwc#s%0=p$moq^$ud^)nl^&i=8'
    ADMIN_PATH = 'admin'
    HASHIDS_SALT = 'fornpunkt'

    LANTMATERIET_USERNAME = os.environ.get('LANTMATERIET_USERNAME')
    LANTMATERIET_PASSWORD = os.environ.get('LANTMATERIET_PASSWORD')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'taggit',
    'django.contrib.sitemaps',
]

TAGGIT_TAGS_FROM_STRING = 'core.utilities.tag_parser'
TAGGIT_STRIP_UNICODE_WHEN_SLUGIFYING = True

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'fornfind.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fornfind.wsgi.application'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'sv-SE'

TIME_ZONE = 'Europe/Amsterdam'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'dashboard'
LOGIN_URL = '/auth/login/'

if 'FP_ENVIRONMENT' in os.environ and os.environ['FP_ENVIRONMENT'] == 'production':
    DEFAULT_FROM_EMAIL = 'support@fornpunkt.se'
    EMAIL_HOST = os.environ['FP_EMAIL_HOST']
    EMAIL_PORT = 587
    EMAIL_HOST_USER = os.environ['FP_EMAIL_USER']
    EMAIL_HOST_PASSWORD = os.environ['FP_EMAIL_PASSWORD']
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
